### ISSUE TITLE
大神请教下 run dev之后报错是为什么

### ISSUE THREAD

**Issue by howyhuang** [eteplus/vue-sui-demo#12]
1.Parsing error: The keyword 'import' is reserved
2.Parsing error: The keyword 'export' is reserved
好像文件里面用到的都在报这个错误

**Comment by zhangtr** [comment]
我也遇到了这个问题，还没解决

**Comment by xlz926** [comment]
升级下node 环境看看

**Comment by huangjihua** [comment]
ESlint的问题，或者node

**Comment by arronf2e** [comment]
我报的是webpack的错，什么原因
