### ISSUE TITLE
第三方js引用怎么切换回本地

### ISSUE THREAD

**Issue by xlz926** [eteplus/vue-sui-demo#16]
目前使用的第三方如 淘宝的 sm.js 怎么切换回在本地目录中加载呢？

* 在app.js 中import ，打包的时候会合并到app.js中。
* 写在webpack的entry 中，当有多个 js 时，默认webpack 会重新排序，不能按自己指定的顺序加载。

是否还有别的方式 写法 能不合并文件加载。

**Comment by naifen00** [comment]
同问

**Comment by naifen00** [comment]
全部放到Main.vue里面 import

**Comment by xlz926** [comment]
全部放到 main.vue中，默认编译后会合并到app.js 中，导致app.js文件过大，能单独出来文件加载么

**Comment by naifen00** [comment]
在dev-server.js配置好跟线上服务器相同的地址
`app.use(staticPath, express.static(path.join(__dirname, '../static')))`
然后就可以在index.html里面 通过标签方式引入
`<script src="staticPath/js/jquery.min.js"></script>`
