### ISSUE TITLE
route或者bar-tab失效？

### ISSUE THREAD

**Issue by 349989153** [eteplus/vue-sui-demo#2]
不太清楚你是不是sui的作者，也许这是sui的问题，不过我先写在这儿吧。

现象是：在home页面的时候，向下拉动页面，但是拉动的长度小于pull-to-refresh的长度，然后放手。
这之后点击bar-tab的任意item，比如“任务”或者“我自己”，对应的view都是一片空白。

**Comment by eteplus** [comment]
我不是sui的作者，这是下拉刷新的bug @349989153
