### ISSUE TITLE
安装后npm run dev总是报缺少各种模块

### ISSUE THREAD

**Issue by yingtianlee** [eteplus/vue-sui-demo#20]
Error: Cannot find module 'mime-db'
安装完后又报
Error: Cannot find module 'minimatch'
安装完又报
Error: Cannot find module 'debug'
....

npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID

**Comment by eteplus** [comment]
建议升级node版本和使用cnpm安装依赖

**Comment by eteplus** [comment]
建议升级node版本（v5.12.0）和使用 cnpm（4.2.0）安装依赖 @yingtianlee

**Comment by yingtianlee** [comment]
@eteplus 执行build时报一下错误
ERROR in ENOENT: no such file or directory, scandir 'E:\code\vue\vue-sui-demo-master\node_modules\node-sass\vendor'
 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-35e55c38&scoped=true!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/views/more.vue 4:14-268

ERROR in ENOENT: no such file or directory, scandir 'E:\code\vue\vue-sui-demo-master\node_modules\node-sass\vendor'
 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/Slider.vue 4:14-243
