### ISSUE TITLE
模块化中的数据来源问题

### ISSUE THREAD

**Issue by niyg** [eteplus/vue-sui-demo#23]
你好，我想请教下，在模块化里面的数据通过http请求返回得到的数据如何作用到当前模块的视图中呢？还是说有更好的数据传递方式，新手望赐教
如图：
![image](https://cloud.githubusercontent.com/assets/14817820/17084189/748c5760-51ea-11e6-9c8a-ea134edd6363.png)

**Comment by eteplus** [comment]
@niyg 定义一个当前模块的变量，把请求得到的数据赋值给这个变量
