### ISSUE TITLE
配置router的时候component用统一的函数生成，为什么webpack就不会splitting code了？

### ISSUE THREAD

**Issue by lomotony** [eteplus/vue-sui-demo#25]
![screenshot - 07282016 - 05 22 14 pm](https://cloud.githubusercontent.com/assets/6621024/17207621/00b40422-54e8-11e6-8969-ff39670cf7cb.png)
我把router.js里的代码改成这样了，但是webpack打包出来就没有chunk文件了，请问这是为什么？

**Comment by eteplus** [comment]
有什么错误提示吗？ @lomotony

**Comment by lomotony** [comment]
![screenshot - 07282016 - 06 26 17 pm](https://cloud.githubusercontent.com/assets/6621024/17209661/ce049fec-54f0-11e6-97cf-774b610b1aef.png)
这个就是打包之后的 @eteplus

**Comment by eteplus** [comment]
你这样把加载组件封装成函数，webpack并不能识别是否是动态组件载入

**Comment by lomotony** [comment]
@eteplus webpack哪里有文档关于这部分的描述吗？
