### ISSUE TITLE
+##### 环境  + 1. node v5.5.0  + 2. npm 3.3.9  readme.md 说明更新一下

### ISSUE THREAD

**Issue by xmllein** [eteplus/vue-sui-demo#26]

**Comment by Evansy** [comment]
打包之后文件运行会出问题，路径报错额

**Comment by eteplus** [comment]
提示什么错误？

**Comment by Evansy** [comment]
`GET http://localhost:8080/src/assets/data/tasks.json 404 (Not Found)`
`GET http://localhost:8080/src/assets/data/banner.json 404 (Not Found)`
`Uncaught (in promise) Response {url: "src/assets/data/banner.json", body: "Cannot GET /src/assets/data/banner.json↵", headers: Object, status: 404, statusText: "Not Found"…}`
