### ISSUE TITLE
指令中的问题。

### ISSUE THREAD

**Issue by niyg** [eteplus/vue-sui-demo#27]
![image](https://cloud.githubusercontent.com/assets/14817820/17241505/98a26fd2-55a4-11e6-91a0-8435b1c7595c.png)
我在框架中并没有看到有zepto 依赖，只是在界面上引入的cdn资源，为什么这边可以直接 import $ from "zepto" 呢？有何用意吗？

**Comment by eteplus** [comment]
在webpack配置里设置 externals ，让webpack知道zepto是全局引入的

**Comment by anyone-yuren** [comment]
谢谢。
