### ISSUE TITLE
发布build之后，只能部署到根目录

### ISSUE THREAD

**Issue by adonishong** [eteplus/vue-sui-demo#30]
npm run build之后出来的结果只能部署到网站的根目录，否则各种路径都会出问题。

**Comment by eteplus** [comment]
@adonishong 可根据webpack配置文件修改目录

**Comment by adonishong** [comment]
是不是可以允许项目直接部署到任意目录？对webpack不是特别熟悉，如果问题问得低级了还请包涵^_^。如果无法实现一次编译就可以部署到任意目录，那我就老老实实研究webpack去了
