### ISSUE TITLE
部署到服务器路由不能刷新

### ISSUE THREAD

**Issue by zhaomin94** [eteplus/vue-sui-demo#35]
部署到服务器，当开启 history 选项(html5模式)时，#号去掉了，直接访问链接时会遇到404，关闭history 选项(html5模式)，可以访问，但是产生了#号，我看了作者的demo两者都做得很完美，还望指点一下

**Comment by eteplus** [comment]
根据配置服务器，参考http://router.vuejs.org/zh-cn/options.html @zhaomin94

**Comment by zhaomin94** [comment]
万分感谢，谢谢，第一次使用框架，很多地方都不懂
