### ISSUE TITLE
如果前端静态文件是部署到tomcat工程下，微信公众号如何通过菜单链接到单页面的不同模块去？

### ISSUE THREAD

**Issue by pengshaosu** [eteplus/vue-sui-demo#37]
webpack构建项目成功后，如果是通过webpack监听的话，微信公众号不同菜单可以通过路由连接到这个单页面的不同模块去。
如果我想把前端静态文件部署到tomcat的项目下，而不使用webpack。因为知道这样只能通过index.html访问该单页面，要是想实现不同菜单进入不同模块，该怎么实现，请教下。thx

**Comment by eteplus** [comment]
如果开启了hashbang，{url}/#!/user，如果没有开启则需要配置服务器，详细的修改可参考http://router.vuejs.org/zh-cn/options.html

**Comment by pengshaosu** [comment]
使用hashbang解决了。多谢
