### ISSUE TITLE
找不到json文件

### ISSUE THREAD

**Issue by Liberty-liu** [eteplus/vue-sui-demo#39]
npm run dev   找不到tasks.json和banner.json

**Comment by yuxiaoxia** [comment]
怎么解决这个问题呢？我也遇到这个问题了

**Comment by mankainchen** [comment]
跨域问题。

**Comment by huigeek** [comment]
同样的问题，npm run dev时，找不到package.json文件

**Comment by XIEJUNXIRUOFENG** [comment]
作者更新过了，引用外部的那个static文件就能解决，this.$http.get('/static/data/banner.json')，分别在home.vue和Slider.vue里面
