### ISSUE TITLE
执行npm run dev 报错

### ISSUE THREAD

**Issue by zhilianbi520** [eteplus/vue-sui-demo#46]
![wxid_37hu311um27m21_1476349402257_51](https://cloud.githubusercontent.com/assets/16549630/19343140/8c6c1bce-9167-11e6-95f7-536d31359d57.png)
报错日志~！求解~
0 info it worked if it ends with ok
1 verbose cli [ 'D:\Program Files\nodejs\node.exe',
1 verbose cli   'D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.8
3 info using node@v6.8.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-sui-demo@0.1.5~predev: vue-sui-demo@0.1.5
6 silly lifecycle vue-sui-demo@0.1.5~predev: no script for predev, continuing
7 info lifecycle vue-sui-demo@0.1.5~dev: vue-sui-demo@0.1.5
8 verbose lifecycle vue-sui-demo@0.1.5~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-sui-demo@0.1.5~dev: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\myfuture\vuedemo\node_modules.bin;Z:\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\local\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\bin;Z:\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Windows\System32\Wbem;C:\Windows;C:\Windows\system32;E:\Java\jdk1.7.0_65\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;D:\Program Files\TortoiseSVN\bin;D:\Program Files\nodejs;D:\Program Files\nodejs\node_global;C:\windows\system32;D:\nvwm;D:\Program Files\Git\cmd;D:\Program Files\nodejs;C:\Ruby23-x64\bin;D:\Ruby23-x64\bin;D:\Ruby22\bin;C:\Users\ydbj0129\AppData\Roaming\npm;D:\Program Files\Git\usr\bin\vendor_perl;D:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle vue-sui-demo@0.1.5~dev: CWD: F:\myfuture\vuedemo
11 silly lifecycle vue-sui-demo@0.1.5~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle vue-sui-demo@0.1.5~dev: Returned: code: 1  signal: null
13 info lifecycle vue-sui-demo@0.1.5~dev: Failed to exec dev script
14 verbose stack Error: vue-sui-demo@0.1.5 dev: `node build/dev-server.js`
14 verbose stack Exit st

**Comment by GGCarry** [comment]
同求，我也是这样子
