### ISSUE TITLE
升级到node5.9.1,npm3.7.3 运行项目失败

### ISSUE THREAD

**Issue by hbsndg** [eteplus/vue-sui-demo#6]
错误日志如下：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\program\\nodejs\\node.exe',
1 verbose cli   'D:\\program\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.7.3
3 info using node@v5.9.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-sui-demo@0.1.3~predev: vue-sui-demo@0.1.3
6 silly lifecycle vue-sui-demo@0.1.3~predev: no script for predev, continuing
7 info lifecycle vue-sui-demo@0.1.3~dev: vue-sui-demo@0.1.3
8 verbose lifecycle vue-sui-demo@0.1.3~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-sui-demo@0.1.3~dev: PATH: D:\program\nodejs\node_modules\npm\bin\node-gyp-bin;E:\webworkspace\vue-sui-demo\node_modules\.bin;D:\program\nodejs;d:\program\graphicsmagick-1.3.21-q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\NetSarang;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\program\TortoiseSVN\bin;D:\program\apache\apache-maven-3.2.5\bin;D:\program\java\jdk1.8.0_45/bin;D:\program\nodejs\;D:\program\Ruby21\bin;D:\program\Git\bin;C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files\MySQL\MySQL Server 5.6\bin;D:\program\apache\Apache24\bin;D:\program\php\php5.6.19;D:\program\php\php5.6.19\ext;C:\Users\DELL\AppData\Roaming\npm
10 verbose lifecycle vue-sui-demo@0.1.3~dev: CWD: E:\webworkspace\vue-sui-demo
11 silly lifecycle vue-sui-demo@0.1.3~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle vue-sui-demo@0.1.3~dev: Returned: code: 3221225501  signal: null
13 info lifecycle vue-sui-demo@0.1.3~dev: Failed to exec dev script
14 verbose stack Error: vue-sui-demo@0.1.3 dev: `node build/dev-server.js`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (D:\program\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\program\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid vue-sui-demo@0.1.3
16 verbose cwd E:\webworkspace\vue-sui-demo
17 error Windows_NT 6.1.7600
18 error argv "D:\\program\\nodejs\\node.exe" "D:\\program\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v5.9.1
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error vue-sui-demo@0.1.3 dev: `node build/dev-server.js`
22 error Exit status 3221225501
23 error Failed at the vue-sui-demo@0.1.3 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-sui-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-sui-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-sui-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hbsndg** [comment]
windows7下，改用node5.5.0版本后，npm install  总是不能安装devDependencies下的开发依赖包，最后降级到node 0.12.0版本才能运行本项目

**Comment by eteplus** [comment]
@hbsndg cnpm install --dev 安装devDependencies的依赖包，建议使用cnpm
