### ISSUE TITLE
不能正常使用啊

### ISSUE THREAD

**Issue by MaomaoFE** [eteplus/vue-sui-demo#8]
下载之后npm run dev，不能打开啊

**Comment by hbsndg** [comment]
@WebFEMe windows7下，改用node5.5.0版本后，npm install 总是不能安装devDependencies下的开发依赖包，最后降级到node 0.12.0版本才能运行本项目

**Comment by WebFEMe** [comment]
我是win8的系统

**Comment by zhucuicui** [comment]
是不是每个项目对环境的依赖是不一样的啊，我是win10的系统，npm install时会报错

**Comment by WangXuanHu** [comment]
@zhucuicui 我现在的环境是node 6.4.0， npm 3.10.6， win8，可以运行的
